-- MySQL Script generated by MySQL Workbench
-- Mon May  4 15:00:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WALLTECH
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WALLTECH` ;

-- -----------------------------------------------------
-- Schema WALLTECH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WALLTECH` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `WALLTECH` ;

-- -----------------------------------------------------
-- Table `Commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Commentaires` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Commentaires` (
  `idCom` INT NOT NULL AUTO_INCREMENT,
  `Utilisateur` INT NOT NULL,
  `heureCom` DATE NOT NULL,
  `likecom` INT NULL,
  `filactu` INT NOT NULL,
  `com` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCom`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Utilisateur_idx` ON `Commentaires` (`Utilisateur` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cours` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cours` (
  `idCours` INT NOT NULL AUTO_INCREMENT,
  `Cours` VARCHAR(245) NOT NULL,
  `Utilisateur` INT NOT NULL,
  PRIMARY KEY (`idCours`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Filactu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Filactu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Filactu` (
  `idFil` INT NOT NULL AUTO_INCREMENT,
  `post` VARCHAR(245) NULL,
  `like` INT NULL,
  `heurepost` DATE NULL,
  `Utilisateur` INT NOT NULL,
  PRIMARY KEY (`idFil`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Messages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Messages` (
  `idMessages` INT NOT NULL,
  `Envoyeur` INT NOT NULL,
  `Recepteur` INT NOT NULL,
  `Message` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`idMessages`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Utilisateur` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `motdepasse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Utilisateur2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Utilisateur2` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Utilisateur2` (
  `idUtilisateur2` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `motdepasse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur2`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
